### ISSUE TITLE
s3cmd fails to copy registry

### ISSUE THREAD

**Issue by glogiotatidis** [deis/deis#3002]
I try to backup my registry following the instructions on http://docs.deis.io/en/v1.1.1/managing_deis/backing_up_data/

db_wall copy completes successfully but registry copy fails.

Deis cluster version 1.1.1
Deis cluster has a 5 active apps.
I'm using a fresh s3cmd (git sha 46392d1a83e25acc1d42c42bf8141ebea49568b0)

```
Invoked as: /home/seadog/.virtualenvs/deis/bin/s3cmd -c /home/seadog/.s3cfg sync s3://registry .
Problem: KeyError: 'content-length'
S3cmd:   1.5.0-rc1
python:   2.7.8 (default, Oct 18 2014, 12:50:18) 
[GCC 4.9.1]
environment LANG=en_US.utf8

Traceback (most recent call last):
  File "/home/seadog/.virtualenvs/deis/bin/s3cmd", line 2521, in <module>
    rc = main()
  File "/home/seadog/.virtualenvs/deis/bin/s3cmd", line 2439, in main
    rc = cmd_func(args)
  File "/home/seadog/.virtualenvs/deis/bin/s3cmd", line 1472, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/home/seadog/.virtualenvs/deis/bin/s3cmd", line 945, in cmd_sync_remote2local
    remote_list, src_exclude_list = fetch_remote_list(args[:-1], recursive = True, require_attribs = True)
  File "/home/seadog/.virtualenvs/deis/local/lib/python2.7/site-packages/S3/FileLists.py", line 418, in fetch_remote_list
    objectlist = _get_filelist_remote(uri, recursive = True)
  File "/home/seadog/.virtualenvs/deis/local/lib/python2.7/site-packages/S3/FileLists.py", line 393, in _get_filelist_remote
    _get_remote_attribs(S3Uri(object_uri_str), rem_list[key])
  File "/home/seadog/.virtualenvs/deis/local/lib/python2.7/site-packages/S3/FileLists.py", line 325, in _get_remote_attribs
    'size': int(response['headers']['content-length']),
KeyError: 'content-length'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Inspecting the exception

```
ipdb> uri
<S3UriS3: s3://registry/registry/images/026140c1ef5773709e23935c8e15344d1d85601519f5b13c443f95beee9354bf/layer>
ipdb> response
{'status': 200, 'headers': {}, 'reason': '', 'data': ''}
```

**Comment by bacongobbler** [comment]
We have only one commit on top of s3cmd: https://github.com/deis/s3cmd/commit/46392d1a83e25acc1d42c42bf8141ebea49568b0

I'd report the issue upstream as they'd know more about this than we would.

**Comment by glogiotatidis** [comment]
To make sure that I understand correctly: This is not a bug of deis s3cmd nor of the deis s3 like interface?

I feel that the later maybe the case, since the response from deis is 200 but without headers, reason or data.

**Comment by sforsman** [comment]
We had the same problem - this is indeed a problem with s3cmd and apparently it is fixed in the latest release. The problem would probably go away by just updating the fork since 1.5.0 has been released a few weeks ago.

@glogiotatidis: Meanwhile, you could just install the latest s3cmd and patch it yourself, it's only a few lines :)

**Comment by bacongobbler** [comment]
sounds good. If someone wants to rebase and PR a version bump, we'd be happy to merge it :)

**Comment by aledbf** [comment]
@bacongobbler s3cmd [merged](https://github.com/s3tools/s3cmd/pull/416) a different PR to the proposed by @carmstrong that fixes the original problem connecting to the Ceph S3 store (the bucket name require an A record in dns).
I downloaded s3cmd from upstream and now works without modification.

ping @carmstrong

**Comment by sforsman** [comment]
Great news, thank you.

**Comment by carmstrong** [comment]
I've updated the docs in #3012.

**Comment by glogiotatidis** [comment]
I tried with the latest s3tools/s3cmd and I still get the same error. Tried with both the latest release (1.5.0) https://github.com/s3tools/s3cmd/releases/tag/v1.5.0 and the latest commit on master 57e3e414fe8d136732504385c00d8f2498a38716

Not being able to take backups, blocks me from putting my deis cluster on production or upgrading to the latest Deis version (which maybe fixes the problem?). Do you folks have any alternative ideas on how to take the backup?

**Comment by carmstrong** [comment]
@glogiotatidis I just tested manually given the latest state of #3012 and it worked just fine for me. I did add one note about ensuring that HTTPs mode is disabled. Did you remove `~/.s3cfg` before upgrading to the latest version and re-running `s3cmd --configure` based on the instructions in #3012 (which are probably live on the docs site by the time you read this)?

**Comment by glogiotatidis** [comment]
Nope I still get the error. I managed to take a backup with a patched s3cmd

https://github.com/glogiotatidis/s3cmd/commit/bedca19a47c6bb222d2f61a653ef06d6d3aa061b

I'll try to restore into a new cluster and see if everything is OK. Is there another way to verify that the backups are OK?

**Comment by carmstrong** [comment]
> I'll try to restore into a new cluster and see if everything is OK. Is there another way to verify that the backups are OK?

Ahhh... are you trying to restore back into a live-running cluster? That's not something I've tried. The backup/restore documentation is meant for backing up and restoring to a fresh cluster - that's the only way I've tested it.

**Comment by glogiotatidis** [comment]
I'm not trying to restore into a live-running cluster. The problem occurs when trying to back-up a live-running cluster. 

Now that I managed to get a backup using a patched s3cmd I'll restore into a new cluster and see if the backup is OK.

**Comment by carmstrong** [comment]
I understand now - thanks for clarifying. It may be worth opening an issue upstream on the s3cmd project.

> Now that I managed to get a backup using a patched s3cmd I'll restore into a new cluster and see if the backup is OK.

Sounds like a plan. :+1:

**Comment by mikkoc** [comment]
Just run into the exact same issue, running s3cmd 1.5.0.

@glogiotatidis patch fixed it for me as well!

**Comment by glogiotatidis** [comment]
@mikkoc did you restore the backup and verified that everything looks ok?

**Comment by mikkoc** [comment]
Nope, getting this when trying to create the bucket:

`s3cmd mb s3://db_wal`

`ERROR: Parameter problem: Bucket name 'db_wal' contains disallowed character '_'. The only supported ones are: lowercase us-ascii letters (a-z), digits (0-9), dot (.) and hyphen (-).`

Using s3cmd 1.5.0
