### ISSUE TITLE
setting DEIS_TEST_APP causes tests to fail

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3334]
It seems if `DEIS_TEST_APP` is set to something other than the default, the integration tests will fail.
```console
$ DEIS_TEST_APP=example-ruby-sinatra ./tests/bin/test-integration.sh
...
=== configsample
BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-go#98f37cc
POWERED_BY: the Deis team
ok
git push deis master
Warning: Permanently added '[deis.local3.deisapp.com]:2222,[172.17.8.102]:2222' (RSA) to the list of known hosts.
-----> Fetching custom buildpack
-----> no app detected
 !     A .godir is required. For instructions:
 !     http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku
To ssh://git@deis.local3.deisapp.com:2222/configsample.git
 * [new branch]      master -> master
ok
--- FAIL: TestConfig (28.52s)
	itutils.go:139: App not started (503)
		Body: (<html>
		<head><title>503 Service Temporarily Unavailable</title></head>
		<body bgcolor="white">
		<center><h1>503 Service Temporarily Unavailable</h1></center>
		<hr><center>nginx/1.6.2</center>
		</body>
		</html>
		)
FAIL
```
We should skip that section of the config test if `DEIS_TEST_APP` isn't what we expect, or else create similar tests for the other example apps.

See also #2879.

**Comment by bacongobbler** [comment]
have we fixed this by now? I just have DEIS_TEST_APP always set to example-go so I don't see this issue, but that's because it's a Go app :P

**Comment by mboersma** [comment]
Not fixed yet. We need to make a lookup table per-app, or just skip this test for now if we aren't on the default test app.
