### ISSUE TITLE
Units failing to start with overlay errors v1.11.0

### ISSUE THREAD

**Issue by jeff-lee** [deis/deis#4584]
I'm getting a lot of overlayfs errors on a new v1.11.0 cluster running in AWS.  

Some nodes work fine, but occasionally the logspout and publisher will fail to start with the following errors.  It seems that 50+% of the nodes that I scale up fail with this error.

Oct 08 19:23:15 ip-10-10-16-94.ec2.internal sh[6347]: bec2a6cd0884: Error pulling image (v1.11.0) from deis/logspout, Driver overlay failed to create image rootfs dbfc35752a295175c15febf830ffd73b748f6717237d48981703cd19d8de045e: lstat /var/lib/docker/overlay/8dd8107abd2e22bfd3b45b05733f3d2677d4078b09b5edce56ee3d8677d3c648: no such file or directory
Oct 08 19:23:15 ip-10-10-16-94.ec2.internal sh[6347]: Error pulling image (v1.11.0) from deis/logspout, Driver overlay failed to create image rootfs dbfc35752a295175c15febf830ffd73b748f6717237d48981703cd19d8de045e: lstat /var/lib/docker/overlay/8dd8107abd2e22bfd3b45b05733f3d2677d4078b09b5edce56ee3d8677d3c648: no such file or directory
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal sh[1573]: 2015-10-08 19:23:20.196966 7f220b8b8700  0 mon.ip-10-10-16-94.ec2.internal@0(leader).data_health(16) update_stats avail 94% total 937 GB, used 6068 MB, avail 881 GB
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal systemd[1]: deis-logspout.service: Service hold-off time over, scheduling restart.
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal systemd[1]: Starting deis-logspout...
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal dockerd[980]: time="2015-10-08T19:23:20.237587238Z" level=info msg="GET /v1.19/images/deis/logspout:v1.11.0/history"
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal dockerd[980]: time="2015-10-08T19:23:20.237718085Z" level=error msg="Handler for GET /images/{name:.*}/history returned error: could not find image: no such id: deis/logspout:v1.11.0"
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal dockerd[980]: time="2015-10-08T19:23:20.237736635Z" level=error msg="HTTP Error" err="could not find image: no such id: deis/logspout:v1.11.0" statusCode=404
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal dockerd[980]: time="2015-10-08T19:23:20.252288636Z" level=info msg="POST /v1.19/images/create?fromImage=deis%2Flogspout%3Av1.11.0"
Oct 08 19:23:20 ip-10-10-16-94.ec2.internal sh[6370]: Pulling repository deis/logspout
Oct 08 19:23:21 ip-10-10-16-94.ec2.internal sh[6370]: bec2a6cd0884: Pulling image (v1.11.0) from deis/logspout
Oct 08 19:23:21 ip-10-10-16-94.ec2.internal sh[6370]: bec2a6cd0884: Pulling image (v1.11.0) from deis/logspout, endpoint: https://registry-1.docker.io/v1/
Oct 08 19:23:21 ip-10-10-16-94.ec2.internal dockerd[980]: time="2015-10-08T19:23:21.589866312Z" level=info msg="GET /containers/json"
Oct 08 19:23:21 ip-10-10-16-94.ec2.internal sh[6370]: bec2a6cd0884: Pulling dependent layers
Oct 08 19:23:21 ip-10-10-16-94.ec2.internal sh[6370]: 8dd8107abd2e: Download complete
Oct 08 19:23:21 ip-10-10-16-94.ec2.internal sh[6370]: dbfc35752a29: Pulling metadata
Oct 08 19:23:21 ip-10-10-16-94.ec2.internal sh[6370]: dbfc35752a29: Pulling fs layer
Oct 08 19:23:22 ip-10-10-16-94.ec2.internal sh[6370]: dbfc35752a29: Error downloading dependent layers
Oct 08 19:23:22 ip-10-10-16-94.ec2.internal systemd[1]: deis-logspout.service: Control process exited, code=exited status=1
Oct 08 19:23:22 ip-10-10-16-94.ec2.internal systemd[1]: Failed to start deis-logspout.
Oct 08 19:23:22 ip-10-10-16-94.ec2.internal systemd[1]: deis-logspout.service: Unit entered failed state.
Oct 08 19:23:22 ip-10-10-16-94.ec2.internal systemd[1]: deis-logspout.service: Failed with result 'exit-code'.

**Comment by carmstrong** [comment]
@jeff-lee Can you confirm the version of the host? `cat /etc/os-release` should show the CoreOS version.

**Comment by jeff-lee** [comment]
@carmstrong sure

core@ip-10-10-16-94 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=766.4.0
VERSION_ID=766.4.0
BUILD_ID=
PRETTY_NAME="CoreOS 766.4.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by carmstrong** [comment]
@mboersma Does this sound like the simultaneous pull issues that seemed to have been resolved with recent Docker?

**Comment by mboersma** [comment]
This does look similar to docker/docker#9718. (which is *not* fixed by any extant version of Docker, sadly). What's odd is that the deis/* images are only available from the v1 registry side of the API, which should work around this issue, and that we haven't encountered this in testing.

**Comment by jeff-lee** [comment]
I can reproduce the issue pretty consistently in AWS using the following steps:

1.  Provision a new v1.11.0 cluster ( this usually works ok ).
2.  Copy the launch config and create a new set of nodes with a different tag ( used to isolate application servers )
3.  Start up some new instances using the new launch config

@carmstrong If you want to ssh in to one of the nodes to poke around before I shut it down your keys are there ( 52.23.213.207 ).

Note that I have an open EY ticket from last night on this same issue ( 103806 ).

**Comment by mboersma** [comment]
@jeff-lee: if indeed this is the same Docker bug, the only known workaround is to serialize all `docker pull` operations. That would mean changing Deis' systemd unit files in this fashion:
```
[Unit]
Description=deis-logspout

[Service]
...
ExecStart=/bin/sh -c "IMAGE=`/run/deis/bin/get_image /deis/logspout` && flock -w 600 /var/run/lock/docker docker run --name deis-logspout --rm -v /var/run/docker.sock:/tmp/docker.sock -e ETCD_HOST=$COREOS_PRIVATE_IPV4 -e HOST=$COREOS_PRIVATE_IPV4 -e DEBUG=1 $IMAGE"
...
```

Adding `flock -w 600 /var/run/lock/docker` before `docker run` will allow only one such image to be fetched at a time, with a timeout of 10 minutes. We would need to add that same stanza to all unit files to prevent any possible collision. Much slower, but perhaps safer.

If that's a change that you could try out for us, at least for logspout and publisher, I would be very interested to know if it resolves the issue. I haven't been able to reproduce it yet, but I will keep trying to pin it down.

**Comment by krancour** [comment]
> We would need to refactor the systemd units to have a separate docker pull step that is guarded by flock.

@mboersma we already have that, don't we?  That is to say, the separate step is already there.  It just isn't guarded.

https://github.com/deis/deis/blob/master/deisctl/units/deis-logspout.service#L10

**Comment by mboersma** [comment]
@krancour yes, you're right--I just missed the command because those lines are sooo long. `docker pull` is what needs to be guarded, assuming we are seeing the above-mentioned Docker bug.

**Comment by jeff-lee** [comment]
@carmstrong @mboersma This seems to affect nodes that are added to the cluster as a result of a scaling operation.  I provisioned a new cluster of 3 x m4.2xlarge instances and installed deis which worked fine.  When I tried to scale to 4 members I received the errors on the new node.

All members have the same coreos/docker version:

NAME=CoreOS
ID=coreos
VERSION=766.4.0
VERSION_ID=766.4.0
BUILD_ID=
PRETTY_NAME="CoreOS 766.4.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

Docker version 1.7.1, build df2f73d-dirty

**Comment by krancour** [comment]
> This seems to affect nodes that are added to the cluster as a result of a scaling operation.

This makes sense.  During `deisctl start platform` components are started in serial.  When scaling out, however, any global units Fleet tells the new node to run are going to be started in parallel-- possibly triggering the known Docker issue.

I have been able to reproduce the issue and now I'm getting good results using @mboersma's suggestion-- customizing the deis-logspout and deis-publisher units to use `flock -w 600 /var/run/lock/docker` in conjunction with `deis pull`.  After putting that in place, I've been able to add many dozens of new nodes without issue.

Another thing you might consider-- if using k8s as the scheduler, you can get away with not running the global publisher unit.  That might eliminate the race condition in Docker that causes this since you won't be pulling two docker images with a common layer each time you add a node.

**Comment by carmstrong** [comment]
> customizing the deis-logspout and deis-publisher units to use flock -w 600 /var/run/lock/docker in conjunction with deis pull.

Is that something we can safely PR against the project?

**Comment by krancour** [comment]
@carmstrong maybe.  @jeff-lee seems to be isolating his planes, so logspout and publisher are his only two global units.  This would work very well for him.

For anyone not isolating their planes, the store components are global units as well.  They're not based on Alpine, so they wouldn't race with logspout and publisher, but since all store components are based on a common Ubuntu image, they'll race with each other.  So we'd be talking about adding these sort of locks to something like eight units in total, with separate locks for pulls of Alpine-based images and pulls of Ubuntu-based images.  I can test that out and see how well it works out.

**Comment by jeff-lee** [comment]
So, if I understand the issue correctly any global units ( e.g. custom monitoring, store-admin, etc ) would also need to serialize via flock.

Any user submitted apps running in the data plane should be safe because they're non-global and won't be started in parallel.  This holds true even if a node fails and multiple non-global units are moved to the same node?

**Comment by krancour** [comment]
If a node fails and the non-global units on it get rescheduled to another node, yes... you could still have a problem.  This isn't likely a problem with deis components' units, since the common layers of any deis component's Docker image would already be present on the machine the units fail over to by virtue of the fact that, at minimum, deis-logspout runs absolutely everywhere.

It _could_ be a problem for applications that fail over from one node to another.  @mboersma thoughts?  Do you think we should put flock locks on the pulls in application units?

**Comment by krancour** [comment]
@jeff-lee, @mboersma has pointed out that app images are pulled from our internal registry; not Docker hub.  Our internal registry is still V1 for the moment, so afawk, app pulls wouldn't be affected.

**Comment by carmstrong** [comment]
@jeff-lee We're hoping to merge #4590 as soon as it passes our test suite, and then we'll be cutting Deis v1.11.1. That should alleviate your blockers for getting into production.

/cc @mboersma

**Comment by carmstrong** [comment]
We're also hoping the root issue, https://github.com/docker/docker/issues/9718 is fixed in the next release of Docker (comments on that issue seem to suggest that it's fixed in master).

**Comment by krancour** [comment]
#4590 closed this when it was merged.  I re-opened this because I don't necessarily consider this resolved yet.

@jeff-lee can I ask you to please refresh your units from master and see if #4590 helps you at all?  If it does, we'll be willing to formalize this in a v1.11.1 release.

**Comment by jeff-lee** [comment]
@krancour I tried adding flock earlier and it didn't seem to resolve the issue, but I can pull from master and try again...if github co-operates.  It's giving me intermittent 500s.

Here's what I added to my logspout unit file.

$ fleetctl cat deis-logspout.service | grep flock
ExecStart=/bin/sh -c "IMAGE=`/run/deis/bin/get_image /deis/logspout` && flock -w 600 /var/run/lock/docker docker run --name deis-logspout --rm -v /var/run/docker.sock:/tmp/docker.sock -e ETCD_HOST=$COREOS_PRIVATE_IPV4 -e HOST=$COREOS_PRIVATE_IPV4 -e DEBUG=1 $IMAGE"

**Comment by carmstrong** [comment]
@jeff-lee Just merged. If you could try those units before we cut the release, that would be awesome. You'd have to check out the codebase locally and configure `DEISCTL_UNITS` to point to the directory so that deisctl uses those unit definitions.

**Comment by jeff-lee** [comment]
@carmstrong Preliminary tests looked good, but I'm getting some fleet/etcd errors after shutting down some nodes to test the unit failover.  I only stopped 3/9 nodes so I don't think I lost quorum but I'll need to do some more testing to see if I can narrow things down.  I probably won't have much more to report until tomorrow.

**Comment by carmstrong** [comment]
> I only stopped 3/9 nodes so I don't think I lost quorum

Be careful here - not all etcd members are treated equally. I believe any hosts added to the cluster after the initial cluster size set when creating the discovery URL will by default become proxy nodes.

Let us know if you need help!

**Comment by jeff-lee** [comment]
@carmstrong Yeah, those issues appear to be unrelated.  I'll follow up separately.  This change looks good to me, if you could cut 1.11.1, that would be great. 

Just to be clear - any global units we submit to the cluster ourselves  ( e.g. monitoring ) will need to use a similar serialization work-around?

**Comment by carmstrong** [comment]
> any global units we submit to the cluster ourselves ( e.g. monitoring ) will need to use a similar serialization work-around?

To be truly safe, yes. The more layers in common between images that are being pulled the higher the chance this will occur. If your images are completely different, you can probably go without.

**Comment by jgmize** [comment]
>> any global units we submit to the cluster ourselves ( e.g. monitoring ) will need to use a similar serialization work-around?

> To be truly safe, yes. The more layers in common between images that are being pulled the higher the chance this will occur. If your images are completely different, you can probably go without.

@carmstrong how does deis avoid this issue when deploying multiple apps which may have common base images?

**Comment by mboersma** [comment]
This bug docker/docker#9718 appears to be fixed in what will be Docker 1.9.

**Comment by mboersma** [comment]
This is fixed in general with Deis v1.11.2.
