### ISSUE TITLE
Fail starting the cluster on AWS without Ceph

### ISSUE THREAD

**Issue by gergelyke** [deis/deis#4805]
Hey,

just started to deploy a cluster on AWS without Ceph, following http://docs.deis.io/en/latest/installing_deis/aws/ then http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/, but when I hit `deis start stateless-platform` it hangs, with the following logs:

```
Dec 18 05:00:35 52.31.200.41 logger:  2015-12-18T13:00:35UTC deis-controller[1]: controller: waiting for confd to write initial templates... 
Dec 18 05:00:36 52.31.200.41 logger:  2015-12-18T13:00:36UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 69) 
Dec 18 05:00:36 52.31.200.41 logger:  2015-12-18T13:00:36UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 18 05:00:36 52.31.200.41 logger:  2015-12-18T13:00:36UTC deis-builder[1]: [debug] Output: "2015-12-18T13:00:36Z 7564d012e1bb confd[181]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:36Z 7564d012e1bb confd[181]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:36Z 7564d012e1bb confd[181]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:36Z 7564d012e1bb confd[181]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
Dec 18 05:00:39 52.31.200.41 logger:  2015-12-18T13:00:39UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 72) 
Dec 18 05:00:39 52.31.200.41 logger:  2015-12-18T13:00:39UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 18 05:00:39 52.31.200.41 logger:  2015-12-18T13:00:39UTC deis-builder[1]: [debug] Output: "2015-12-18T13:00:39Z 7564d012e1bb confd[185]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:39Z 7564d012e1bb confd[185]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:39Z 7564d012e1bb confd[185]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:39Z 7564d012e1bb confd[185]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
Dec 18 05:00:42 52.31.200.41 logger:  2015-12-18T13:00:42UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 75) 
Dec 18 05:00:42 52.31.200.41 logger:  2015-12-18T13:00:42UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 18 05:00:42 52.31.200.41 logger:  2015-12-18T13:00:42UTC deis-builder[1]: [debug] Output: "2015-12-18T13:00:42Z 7564d012e1bb confd[190]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:42Z 7564d012e1bb confd[190]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:42Z 7564d012e1bb confd[190]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:42Z 7564d012e1bb confd[190]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
Dec 18 05:00:44 52.31.200.41 logger:  2015-12-18T13:00:44UTC deis-router[1]: [INFO] - waiting for confd to write initial templates... 
Dec 18 05:00:44 52.31.200.41 logger:  2015-12-18T13:00:44UTC deis-router[1]: [INFO] - waiting for confd to write initial templates... 
Dec 18 05:00:44 52.31.200.41 logger:  2015-12-18T13:00:44UTC deis-router[1]: [INFO] - waiting for confd to write initial templates... 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-registry[1]: 2015-12-18T13:00:45Z 215c6c68203c confd[72]: ERROR 100: Key not found (/deis/store) [26513] 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-registry[1]: 2015-12-18T13:00:45Z 215c6c68203c confd[72]: ERROR 100: Key not found (/deis/store) [26513] 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-registry[1]: registry: waiting for confd to write initial templates... 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 78) 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-builder[1]: [debug] Output: "2015-12-18T13:00:45Z 7564d012e1bb confd[195]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:45Z 7564d012e1bb confd[195]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:45Z 7564d012e1bb confd[195]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:45Z 7564d012e1bb confd[195]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-controller[1]: 2015-12-18T13:00:45Z e830f028aaa0 confd[148]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist 
Dec 18 05:00:45 52.31.200.41 logger:  2015-12-18T13:00:45UTC deis-controller[1]: controller: waiting for confd to write initial templates... 
Dec 18 05:00:48 52.31.200.41 logger:  2015-12-18T13:00:48UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 81) 
Dec 18 05:00:48 52.31.200.41 logger:  2015-12-18T13:00:48UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 18 05:00:48 52.31.200.41 logger:  2015-12-18T13:00:48UTC deis-builder[1]: [debug] Output: "2015-12-18T13:00:48Z 7564d012e1bb confd[199]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:48Z 7564d012e1bb confd[199]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:48Z 7564d012e1bb confd[199]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:48Z 7564d012e1bb confd[199]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
Dec 18 05:00:51 52.31.200.41 logger:  2015-12-18T13:00:51UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 84) 
Dec 18 05:00:51 52.31.200.41 logger:  2015-12-18T13:00:51UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 18 05:00:51 52.31.200.41 logger:  2015-12-18T13:00:51UTC deis-builder[1]: [debug] Output: "2015-12-18T13:00:51Z 7564d012e1bb confd[204]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:51Z 7564d012e1bb confd[204]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:51Z 7564d012e1bb confd[204]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:51Z 7564d012e1bb confd[204]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
Dec 18 05:00:54 52.31.200.41 logger:  2015-12-18T13:00:54UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 87) 
Dec 18 05:00:54 52.31.200.41 logger:  2015-12-18T13:00:54UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 18 05:00:54 52.31.200.41 logger:  2015-12-18T13:00:54UTC deis-builder[1]: [debug] Output: "2015-12-18T13:00:54Z 7564d012e1bb confd[209]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:54Z 7564d012e1bb confd[209]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:54Z 7564d012e1bb confd[209]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-12-18T13:00:54Z 7564d012e1bb confd[209]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
Dec 18 05:00:54 52.31.200.41 logger:  2015-12-18T13:00:54UTC deis-router[1]: [INFO] - waiting for confd to write initial templates... 
Dec 18 05:00:54 52.31.200.41 logger:  2015-12-18T13:00:54UTC deis-router[1]: [INFO] - waiting for confd to write initial templates... 
Dec 18 05:00:55 52.31.200.41 logger:  2015-12-18T13:00:54UTC deis-router[1]: [INFO] - waiting for confd to write initial templates... 
Dec 18 05:00:55 52.31.200.41 logger:  2015-12-18T13:00:55UTC deis-registry[1]: 2015-12-18T13:00:55Z 215c6c68203c confd[77]: ERROR 100: Key not found (/deis/store) [26562] 
Dec 18 05:00:55 52.31.200.41 logger:  2015-12-18T13:00:55UTC deis-registry[1]: 2015-12-18T13:00:55Z 215c6c68203c confd[77]: ERROR 100: Key not found (/deis/store) [26562] 
Dec 18 05:00:55 52.31.200.41 logger:  2015-12-18T13:00:55UTC deis-registry[1]: registry: waiting for confd to write initial templates... 
Dec 18 05:00:55 52.31.200.41 logger:  2015-12-18T13:00:55UTC deis-controller[1]: 2015-12-18T13:00:55Z e830f028aaa0 confd[154]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist 
```

Any idea?

**Comment by MaxenceAdnot** [comment]
Hi,

A component is obviously failing here and confd templates can't be filled.

It may be related to the S3 bucket creation. I experienced similar errors recently due to a boto error with a python trace (even after the recent patch). Could you have a look to the logs for the registry component ?

If you don't find anything on the registry component you should check the components logs in the deisctl starting order to determine which one failed.

**Comment by gergelyke** [comment]
Hm,

just found something that may be connected: 

```
2015-12-18T10:59:45UTC deis-registry[1]: registry: environment ETCD=10.21.2.109:4001 ETCD_PATH=/deis/registry HOST_ETCD_PATH=/deis/registry/hosts/10.21.2.109 ETCD_TTL=20 REGISTRY_PORT=5000 EXTERNAL_PORT=5000 BUCKET_NAME=registry 
```

In the bucket name, should it be the S3 Bucket? if so, from where does it come from?

**Comment by bacongobbler** [comment]
That's a default bucket name. You should be fine. It comes from [here](https://github.com/deis/deis/blob/v1.12.2/registry/bin/boot#L22)

As far as the logs, what's the output of `deisctl journal registry@1` for you? Do you get any output similar to https://github.com/deis/deis/issues/4772?

**Comment by iancoffey** [comment]
@gergelyke seems like the registry isnt starting because the store etcd keys are missing, which is an issue I thought we fixed. What version are you running?

If that is indeed the case, a work around might be to just create a dummy key under store.

`etcdctl set /deis/store/gateway/helloWorld 1`

**Comment by Blystad** [comment]
You're probably encountering this issue: https://github.com/deis/deis/issues/4710

Setting the dummy etcd should fix it.

**Comment by MaxenceAdnot** [comment]
If I may put my two cents in, I'm still experiencing boto errors similar to #4772 

The fix I apply is to define deis/gateway/host and deis/gateway/port keys with one of the HTTPS S3 endpoints (as it needs a secure endpoint in this case - see https://github.com/deis/deis/blob/master/registry/templates/create_bucket). I will create a separate issue for that but it may be working for this case if the error is linked...

**Comment by gergelyke** [comment]
@iancoffey i was trying with the latest master and 1.12.2, but now will try this fix as well - will keep you informed, thanks!

**Comment by gergelyke** [comment]
Hey,

just tried both the dummy key, and the `/deis/store/gateway/accessKey`, I encounter a new error (version 1.12.2):

```
Dec 21 00:30:49 52.30.235.24 logger:  2015-12-21T08:30:49UTC deis-builder[1]: [info] Re-trying template build. (Elapsed time: 425) 
Dec 21 00:30:49 52.30.235.24 logger:  2015-12-21T08:30:49UTC deis-builder[1]: [debug] Recoverable error: exit status 1 
Dec 21 00:30:49 52.30.235.24 logger:  2015-12-21T08:30:49UTC deis-builder[1]: [debug] Output: "2015-12-21T08:30:49Z 684b36e500fc confd[1094]: ERROR template: builder:79:49: executing \"builder\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n2015-12-21T08:30:49Z 684b36e500fc confd[1094]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n" 
```

any idea what am I missing?

**Comment by iancoffey** [comment]
@gergelyke looks like builders failing to start due to a missing controller key.

What does `etcdctl ls /deis/controller` look like? It should exist and needs to have a few keys present (protocol, host, port and builderKey iirc) to be able to start.

**Comment by gergelyke** [comment]
thanks - the problem was totally on my side, Deis couldn't reach the Postgre server :(
